apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          ports:
            - containerPort: 7575
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: homarr-secrets
                  key: SECRET_ENCRYPTION_KEY
          volumeMounts:
            - name: config
              mountPath: /appdata
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homarr-config
