---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secrets
  namespace: media
spec:
  encryptedData:
    SECRET_ENCRYPTION_KEY: AgCetZbr/w34mlGNrE6tbfQ5E4Jg3eiMRgDN7+Z0jlHa4IqjzIa+KAm6L/PCesVz6OZ5LAkXsC7GodelQRKuIbZwxD1h/Zah+oNPTdwAyP07tMo2Wm8rjend/GLM577FdSO8e5XDTbSaydsQmElkdCRRJ456Xj95CqIe1p/sg/Gdlt5UY6N6wAIcZ9p1fpH2+eZCfAvhVnI3RTsYqWrVwM7vcOZiCdOim0K+X4R9X9/SZUUNNOviOdpHvBWAYAfSeb/bwq/4aLd+fDIXvmo9p6CQjoKxeiPkZPu3r3PWZiogiu0iIduMWfSnITn+158jEVWVaKsG4sSJjT3r9nymT12MtNuTZKIRcrcGpv1BaXBVeg3xuNde+iu3kksv+SBE8291yslOg5/JOWYNqR1UAPkOxnujzTB1J1dcXWjYf2KhOH0bppKXhNB3ZDrTAI48c4wZ+iF7r22pcyZ2YNK3w3zlMGJXJNJM4gWFjfyaD554XwnBQRo2NTmnq/Mh3gR67631bzVuzz+C0DRhPoL6vpIHa9mPzwVk1xl8OfMbrteRTbJBR+2BGFtfSAlG6AKOrOBmNGi/MlU/ejE7zJYgKuM6APyt4f3OEJG8RRAzJNqwPI0G673g2w3g6e8vYYan/wIdHW7dPbgVid5QAVBqX2TJzSP7rjzwR5o+g47cC8kQTgikmtPD8zR8yWA0OOV6/szq6EtbABdfmhFUoJqAzO34cgp7PumOQy/XKqRysq2tlSabi4f5Kjnft5yMT6Olc9DXJX4rDlRjoY4h22G5J48M
  template:
    metadata:
      name: homarr-secrets
      namespace: media
