apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
    spec:
      containers:
        - name: jellyseer
          image: fallenbagel/jellyseer:latest
          ports:
            - containerPort: 5055
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyseer-config
