apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseer-http
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jellyseer.thijsvdweijer.nl`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseer-https
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseer.thijsvdweijer.nl`)
      kind: Rule
      services:
        - name: jellyseer
          port: 5055
  tls:
    secretName: jellyseer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseer-tls
  namespace: media
spec:
  secretName: jellyseer-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - jellyseer.thijsvdweijer.nl
