apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
spec:
  storageClassName: nfs-downloads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
